Add `AllocationGroupId`.
tobz/tracking-allocator pull request #2
Opened 2022-01-31 23:04 UTC by jswrenn

This PR allows users to correlate between the `group_id` of allocation events and `AllocationGroupToken`. Specifically:
- A new `AllocationGroupToken::id` method turns an `AllocationGroupToken` into an `AllocationGroupId`.
- The `group_id` parameter of `AllocationTracker::allocated` is now a `AllocationGroupId`.

Unlike `AllocationGroupToken`, the `AllocationGroupId` type may be freely copied, compared and hashed.

2022-02-01 00:14 UTC, tobz requested changes
Overall, looks good, but one small comment/nit.

2022-02-01 01:33 UTC, jswrenn commented on src/token.rs
> +pub struct AllocationGroupId(usize);
I'm not far enough along with my experiments to say that it *needs* to be `Clone`, but working with non-Clone types is really painful; my inclination is to always implement `Clone` unless cloning poses some hazard. It's far easier, for instance, to put `AllocationGroupId` in a [bimap](https://docs.rs/bimap/latest/bimap/) or multiple `HashMap`s if it's `Clone`.

2022-02-01 14:43 UTC, jswrenn commented on src/token.rs
> +pub struct AllocationGroupId(usize);
Removed the `Copy` impl!

2022-02-02 01:37 UTC, tobz approved these changes

2022-02-02 01:38 UTC, merged